name: Compile an publish PDF

on:
    push:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "systems/**"
            - CNAME
            - "**.html"
            - "**.tex"
    pull_request:
        branches:
            - main
        paths:
            - ".github/workflows/**"
            - "systems/**"
            - CNAME
            - "**.html"
            - "**.tex"
    workflow_dispatch: # Allows manual execution of workflow

jobs:
    build-latex:
        runs-on: ubuntu-latest
        container:
            image: danteev/texlive:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  persist-credentials: false

            - name: Compile LaTeX document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: |
                    resume.tex
                    systems/systems-resume.tex

            - name: Post Processing
              run: |
                  mkdir build 
                  mkdir build/systems
                  cp systems/*.html build/systems/
                  cp systems-resume.pdf build/systems/
                  mv build/systems/systems-resume.pdf "build/systems/Pranav Dani Résumé Systems.pdf"
                  cp resume.pdf build/ 
                  cp *.html build/
                  cp CNAME build/
                  mv "build/resume.pdf" "build/Pranav Dani Résumé.pdf"
            
            - name: Git add
              run: |
                  git config --global --add safe.directory '*'
                  git add *.pdf

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  BRANCH: gh-pages
                  FOLDER: build
                  CLEAN: true
